@startuml DiagramaCasosDeUso_ONGVOA

left to right direction

actor "Padrinho (Doador)" as Padrinho
actor "Administrador (ONG VOA)" as Admin

rectangle SistemaNatalVOA {
    usecase "Visualizar Desejos Disponíveis" as CU01
    usecase "Reservar Presente" as CU02
    usecase "Autenticar no Sistema" as CU05
    usecase "Gerenciar Idosos e Desejos" as CU03
    usecase "Monitorar Apadrinhamentos" as CU04
}

Padrinho --> CU01
Padrinho --> CU02

Admin --> CU05
Admin --> CU03
Admin --> CU04

CU03 ..> CU05 : <<include>>
CU04 ..> CU05 : <<include>>

@enduml